// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajmlcrsukpldsghxzabi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqbWxjcnN1a3BsZHNnaHh6YWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMzk5MTcsImV4cCI6MjA2NjgxNTkxN30.T6ymps7BMSv6fHYoj_WGEoH_DTZUKcrTh0Yer4W3L1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});